/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAttendeesRouteImport } from './routes/admin/attendees'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCheckInsRouteImport } from './routes/admin/check-ins'
import { Route as AdminFaqsRouteImport } from './routes/admin/faqs'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminProgrammeRouteImport } from './routes/admin/programme'
import { Route as AdminSpeakersRouteImport } from './routes/admin/speakers'
import { Route as TicketTokenRouteImport } from './routes/ticket.$token'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api/payments/webhook'
import { Route as ApiAdminTicketsAttendeeIdResendRouteImport } from './routes/api/admin/tickets/$attendeeId/resend'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendeesRoute = AdminAttendeesRouteImport.update({
  id: '/attendees',
  path: '/attendees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckInsRoute = AdminCheckInsRouteImport.update({
  id: '/check-ins',
  path: '/check-ins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgrammeRoute = AdminProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpeakersRoute = AdminSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => AdminRoute,
} as any)
const TicketTokenRoute = TicketTokenRouteImport.update({
  id: '/ticket/$token',
  path: '/ticket/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTicketsAttendeeIdResendRoute =
  ApiAdminTicketsAttendeeIdResendRouteImport.update({
    id: '/api/admin/tickets/$attendeeId/resend',
    path: '/api/admin/tickets/$attendeeId/resend',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/check-in': typeof CheckInRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/register': typeof RegisterRoute
  '/admin/attendees': typeof AdminAttendeesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/check-ins': typeof AdminCheckInsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/programme': typeof AdminProgrammeRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/ticket/$token': typeof TicketTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/admin/tickets/$attendeeId/resend': typeof ApiAdminTicketsAttendeeIdResendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/register': typeof RegisterRoute
  '/admin/attendees': typeof AdminAttendeesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/check-ins': typeof AdminCheckInsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/programme': typeof AdminProgrammeRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/ticket/$token': typeof TicketTokenRoute
  '/admin': typeof AdminIndexRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/admin/tickets/$attendeeId/resend': typeof ApiAdminTicketsAttendeeIdResendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/check-in': typeof CheckInRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/register': typeof RegisterRoute
  '/admin/attendees': typeof AdminAttendeesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/check-ins': typeof AdminCheckInsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/programme': typeof AdminProgrammeRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/ticket/$token': typeof TicketTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/admin/tickets/$attendeeId/resend': typeof ApiAdminTicketsAttendeeIdResendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/check-in'
    | '/payment-success'
    | '/register'
    | '/admin/attendees'
    | '/admin/categories'
    | '/admin/check-ins'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/programme'
    | '/admin/speakers'
    | '/ticket/$token'
    | '/admin/'
    | '/api/payments/webhook'
    | '/api/admin/tickets/$attendeeId/resend'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in'
    | '/payment-success'
    | '/register'
    | '/admin/attendees'
    | '/admin/categories'
    | '/admin/check-ins'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/programme'
    | '/admin/speakers'
    | '/ticket/$token'
    | '/admin'
    | '/api/payments/webhook'
    | '/api/admin/tickets/$attendeeId/resend'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/check-in'
    | '/payment-success'
    | '/register'
    | '/admin/attendees'
    | '/admin/categories'
    | '/admin/check-ins'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/programme'
    | '/admin/speakers'
    | '/ticket/$token'
    | '/admin/'
    | '/api/payments/webhook'
    | '/api/admin/tickets/$attendeeId/resend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckInRoute: typeof CheckInRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  RegisterRoute: typeof RegisterRoute
  TicketTokenRoute: typeof TicketTokenRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
  ApiAdminTicketsAttendeeIdResendRoute: typeof ApiAdminTicketsAttendeeIdResendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendees': {
      id: '/admin/attendees'
      path: '/attendees'
      fullPath: '/admin/attendees'
      preLoaderRoute: typeof AdminAttendeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/check-ins': {
      id: '/admin/check-ins'
      path: '/check-ins'
      fullPath: '/admin/check-ins'
      preLoaderRoute: typeof AdminCheckInsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programme': {
      id: '/admin/programme'
      path: '/programme'
      fullPath: '/admin/programme'
      preLoaderRoute: typeof AdminProgrammeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/speakers': {
      id: '/admin/speakers'
      path: '/speakers'
      fullPath: '/admin/speakers'
      preLoaderRoute: typeof AdminSpeakersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ticket/$token': {
      id: '/ticket/$token'
      path: '/ticket/$token'
      fullPath: '/ticket/$token'
      preLoaderRoute: typeof TicketTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tickets/$attendeeId/resend': {
      id: '/api/admin/tickets/$attendeeId/resend'
      path: '/api/admin/tickets/$attendeeId/resend'
      fullPath: '/api/admin/tickets/$attendeeId/resend'
      preLoaderRoute: typeof ApiAdminTicketsAttendeeIdResendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAttendeesRoute: typeof AdminAttendeesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCheckInsRoute: typeof AdminCheckInsRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProgrammeRoute: typeof AdminProgrammeRoute
  AdminSpeakersRoute: typeof AdminSpeakersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttendeesRoute: AdminAttendeesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCheckInsRoute: AdminCheckInsRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProgrammeRoute: AdminProgrammeRoute,
  AdminSpeakersRoute: AdminSpeakersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckInRoute: CheckInRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  RegisterRoute: RegisterRoute,
  TicketTokenRoute: TicketTokenRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
  ApiAdminTicketsAttendeeIdResendRoute: ApiAdminTicketsAttendeeIdResendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
